apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gatesway
    type: microservice
spec:
  containers:
    - name: gateway-app
      image: maniortiz/serviciosapigateway:latest
      ports:
        - containerPort: 80