apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-deploy
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-seguridad
      type: microservice
  template:
    metadata: 
        name: microservice-seguridad-pod
        labels: 
          app: microservice-seguridad
          type: microservice
    spec:
        containers:
        - name: microservice-seguridad-app
          image: maniortiz/serviciosapiseguridad:latest
          ports: 
            - conteinerPort: 80
          env:
            - name: ConnectionStrings__ConexionDB
              value: Server=mssql-service;Database=Seguridad;User=sa;Password=$ManiOrtiz2025